### ISSUE TITLE
TrafficMonitor doesn't seem to get the correct name from network adapters...

### ISSUE THREAD

**Issue by kator-278** [zhongyang219/TrafficMonitor#116]
Hello author.
This program works fine in one of my computers. I'm about to swap out NetSpeedMonitor since it's been out of date for a very long time.
But when I'm preparing to use it in another computer, it seems to be failed to show up any speed:
![](https://user-images.githubusercontent.com/8875998/43305669-38666714-91ab-11e8-9b13-5f6a9b57c7bb.png)

A simple recheck shows that this program doesn't get the corrected name from my network adapter (doubtly due to containing some chinese characters):
![](https://user-images.githubusercontent.com/8875998/43305681-3eb0cbfa-91ab-11e8-8c14-18438829a49e.png)

The configuration about section `[connection]` in `config.ini`:
```
[connection]
auto_select=0
select_all=0
connection_name="Broadcom 802.11n "
```

Error message in `error.log`:
```
2018/07/27 11:47:43.701: An exception may have occurred, the currently selected connection is inconsistent with the expected connection. The connection has been retrieved. (1 times has been reinitialized)
2018/07/27 11:47:46.747: An exception may have occurred, the currently selected connection is inconsistent with the expected connection. The connection has been retrieved. (2 times has been reinitialized)
2018/07/27 11:47:49.791: An exception may have occurred, the currently selected connection is inconsistent with the expected connection. The connection has been retrieved. (3 times has been reinitialized)
...
2018/07/27 11:57:44.199: An exception may have occurred, the currently selected connection is inconsistent with the expected connection. The connection has been retrieved. (137 times has been reinitialized)
```

Even though I explicitly assigned a corrected value for `connection_name` (in either UTF-8 or GBK format), the program just overrides it with his incorrect one instead of trying to find if there's such a network adapter, and then keeps generating same error logs.

What should I do next to prevent this happening?
Thank you.

**Comment by zhongyang219** [comment]
Thanks for your feedback, this is indeed a bug. In fact, I have noticed it before. The reason is, in some computers, the adapter names acquired from API GetIfTable and GetAdaptersInfo is not the same. In your examples, connection name acquired from GetIfTable is "Broadcom 802.11n 网络适配器", and witch acquired from GetAdaptersInfo is "Broadcom 802.11n".
In the version1.73 and before, I only use  GetIfTable to get the connections. But it contains all of the interfaces, include the IPv4 loopback interface. In version 1.74, I use  GetAdaptersInfo to get the adopter name, which dose not include the loopback interface. (The adaptor names in the right click menu is acquired by GetAdaptersInfo.) And then find the corresponding interface name in the result from GetIfTable. I thought the name acquired from the two APIs would be the same, but I was wrong. If it cannot find the adapter name in the result from GetIfTable, the bug occurs. 
I have fixed this bug, please wait for update. If you occurred this problem, as a temporary solution, you can use version 1.73 instead.

**Comment by zhongyang219** [comment]
[TrafficMonitor_1.7.4.1(beta).zip](https://github.com/zhongyang219/TrafficMonitor/files/2247839/TrafficMonitor_1.7.4.1.beta.zip)
This is an unreleased version. You can try it and tell me if you problem is solved.

**Comment by kator-278** [comment]
Thanks for your response and fix.
Just tried the v1.74.1 beta version. It can show network speed normally now:
<p align="center"><img src="https://user-images.githubusercontent.com/8875998/43519613-bb473dbe-95c2-11e8-9fa1-203ad1c2fe33.png"/></p>

Yet the program still keeps generating error logs like this:
```
2018/08/01 19:42:52.955: An exception may have occurred, the currently selected connection is inconsistent with the expected connection. The connection has been retrieved. (168 times has been reinitialized)
```

There may be still some extra works to do, but good to let me know about those details.

Here's some name-related information about my network adapter, hope it would help.
<p align="center"><img src="https://user-images.githubusercontent.com/8875998/43520257-d809b7cc-95c4-11e8-81d5-a48d1c20122c.png"/></p>

**Comment by zhongyang219** [comment]
Thanks for your feedback. I will investigate on this problem.

**Comment by zhongyang219** [comment]
Hello, this problem may have solved. It should not continue to generate the error logs now. You can try this: [TrafficMonitor_1.7.4.2(beta).zip](https://github.com/zhongyang219/TrafficMonitor/files/2253360/TrafficMonitor_1.7.4.2.beta.zip)
and tell me if the problem is solved.

**Comment by kator-278** [comment]
Yeah now it is fine. The error logs are no longer generated, and the `connection_name` in `config.ini` is correct.
Sincerely thanks for the bugfix, much appreciated.
