### ISSUE TITLE
Taskbar options totally broken

### ISSUE THREAD

**Issue by junesties** [zhongyang219/TrafficMonitor#1344]
![Screenshot 2022-10-05 175242](https://user-images.githubusercontent.com/54336066/194105745-07ba5939-a950-4184-b772-ab9114fa30b5.png)
![Screenshot 2022-10-05 175300](https://user-images.githubusercontent.com/54336066/194105762-f8855f39-2106-4706-8987-5189a6c2c6ff.png)
![Screenshot 2022-10-05 175318](https://user-images.githubusercontent.com/54336066/194105769-51c7ee77-8a38-4dc5-a0bb-b990870b288f.png)

So, I updated to 1.84 but this is completly broken with centered taskbar. Some of the options work as intented, but prioritizing

> Taskbar window appears to the left of the taskbar

Doesn't work in any case. So it seems like the right side of the icon bar acts as the "left side" of the taskbar only at the other option is now not usable. Event ticked alone (as shown in the screenshot) it doesn't align to the left side of my taskbar, it gets aligned to the right side.

**Comment by Shubham123498765** [comment]
https://github.com/zhongyang219/TrafficMonitor/issues/1335#issuecomment-1268358227

**Comment by junesties** [comment]
> https://github.com/zhongyang219/TrafficMonitor/issues/1335#issuecomment-1268358227

Hm, I downloaded the 64Bit zip packed version. But I'll try the linked one. Thanks.

**Comment by Shubham123498765** [comment]
Yes, I was also facing the same issue. Download this you will be good to go.

**Comment by junesties** [comment]
> Yes, I was also facing the same issue. Download this you will be good to go.

Thanks for information. I'll mark this as solved after I tested it myself!

**Comment by junesties** [comment]
> Yes, I was also facing the same issue. Download this you will be good to go.

still no fix, same problem

**Comment by NewRavenGer** [comment]
Same issue here. The "show on the left side" option doesn't anything plus the spacing isn't working correctly either... if you show too many values, the text either clips into the systray icons or into the taskbar icons which renders both unclickable. It should instead just cut off or something like that. Also, the "trasparent background" option randomly resets itself sometimes after some restarts - but it already did that in 1.83

**Comment by junesties** [comment]
> Same issue here. The "show on the left side" option doesn't anything plus the spacing isn't working correctly either... if you show too many values, the text either clips into the systray icons or into the taskbar icons which renders both unclickable. It should instead just cut off or something like that. Also, the "trasparent background" option randomly resets itself sometimes after some restarts - but it already did that in 1.83


Sadly, the fix that was provided by a user has now an invalid link.  So the old fix isn't available for the 1.83 anymore.

**Comment by Shubham123498765** [comment]
Send me your email ID, I have downloaded the zip file already ,I will mail
it to you.

**Comment by zhongyang219** [comment]
In version 1.84, if the taskbar window is aligned to the left, the taskbar window will always appear on the right because it overlaps the original taskbar button when shown on the left.
The program detects taskbar alignment by reading the key value of "TaskbarAl" in the registry "\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced". But if you never change the alignment settings of the taskbar, this key is not exist and TrafficMonitor mistakenly thinks the taskbar is left aligned. This is a bug. The solution is:
Click the right mouse button in the taskbar, select Taskbar Settings, and change the alignment method of the taskbar once. After generating the above key value, for example, change "center" to "Align left", and then change it back to "center".
